### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by ChristopherHaws** [HousebirdGames/Commands-Explorer#1]
I would love to be able to right click and favorite different commands so they show up in a separate group at the top of the tree or in their own view container.

Thanks!

**Comment by HousebirdGames** [comment]
Hey!
Thank you for your suggestion. I'm pleased to inform you that this feature has been implemented in the new version 1.1.0. I hope you find it useful.

In addition, I've introduced an option that allows you to choose whether you want your favorites to be synced across devices (which is enabled by default) or kept local. There's also a new setting that lets you decide if you want the favorite commands to be displayed in both their original groups and the favorites group, or only in the favorites group.

I appreciate your feedback and look forward to any further suggestions you might have.
